### ISSUE TITLE
OPenGL error

### ISSUE THREAD

**Issue by bilel-bj** [mkocabas/VIBE#10]
An error in OpenGL occured, Please see the below output:
Thanks for your support

`python demo.py --vid_file sample_2.mp4 --output_folder output/ --display
Running "ffmpeg -i sample_2.mp4 -f image2 -v error /tmp/sample_2_mp4/%06d.png"
Images saved to "/tmp/sample_2_mp4"
Input video number of frames 1013
Running Multi-Person-Tracker
100%|███████████████████████████████████████████| 85/85 [04:14<00:00,  2.99s/it]
Finished. Detection + Tracking FPS 3.99
Displaying results..
=> loaded pretrained model from 'data/vibe_data/spin_model_checkpoint.pth.tar'
Performance of pretrained model on 3DPW: 56.56075477600098
Loaded pretrained weights from "data/vibe_data/vibe_model_wo_3dpw.pth.tar"
Running VIBE on each tracklet...
100%|████████████████████████████████████████████████████████████████████████████████████████| 2/2 [02:09<00:00, 64.92s/it]
VIBE FPS: 7.80
Total time spent: 394.83 seconds (including model loading time).
Total FPS (including model loading time): 2.57.
Saving output results to "output/sample_2/vibe_output.pkl".
Rendering output video, writing frames to /tmp/sample_2_mp4_output
  6%|█████▏                                                                              | 63/1013 [00:01<00:19, 48.56it/s]
Traceback (most recent call last):
  File "/home/riotu/VIBE/vibe/lib/python3.7/site-packages/OpenGL/latebind.py", line 41, in __call__
    return self._finalCall( *args, **named )
TypeError: 'NoneType' object is not callable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 377, in <module>
    main(args)
  File "demo.py", line 292, in main
    mesh_filename=mesh_filename,
  File "/home/riotu/VIBE/lib/utils/renderer.py", line 118, in render
    rgb, _ = self.renderer.render(self.scene, flags=render_flags)
  File "/home/riotu/VIBE/vibe/lib/python3.7/site-packages/pyrender/offscreen.py", line 99, in render
    return self._renderer.render(scene, flags)
  File "/home/riotu/VIBE/vibe/lib/python3.7/site-packages/pyrender/renderer.py", line 121, in render
    self._update_context(scene, flags)
  File "/home/riotu/VIBE/vibe/lib/python3.7/site-packages/pyrender/renderer.py", line 709, in _update_context
    p._add_to_context()
  File "/home/riotu/VIBE/vibe/lib/python3.7/site-packages/pyrender/primitive.py", line 324, in _add_to_context
    self._vaid = glGenVertexArrays(1)
  File "/home/riotu/VIBE/vibe/lib/python3.7/site-packages/OpenGL/latebind.py", line 45, in __call__
    return self._finalCall( *args, **named )
  File "/home/riotu/VIBE/vibe/lib/python3.7/site-packages/OpenGL/wrapper.py", line 657, in wrapperCall
    result = wrappedOperation( *cArguments )
  File "/home/riotu/VIBE/vibe/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 401, in __call__
    if self.load():
  File "/home/riotu/VIBE/vibe/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 390, in load
    error_checker = self.error_checker,
  File "/home/riotu/VIBE/vibe/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 148, in constructFunction
    if (not is_core) and not self.checkExtension( extension ):
  File "/home/riotu/VIBE/vibe/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 270, in checkExtension
    result = extensions.ExtensionQuerier.hasExtension( name )
  File "/home/riotu/VIBE/vibe/lib/python3.7/site-packages/OpenGL/extensions.py", line 98, in hasExtension
    result = registered( specifier )
  File "/home/riotu/VIBE/vibe/lib/python3.7/site-packages/OpenGL/extensions.py", line 105, in __call__
    if not specifier.startswith( self.prefix ):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
`

**Comment by bilel-bj** [comment]
This solved my issue: https://github.com/mcfletch/pyopengl/issues/27

**Comment by mkocabas** [comment]
Thanks for the solution!

**Comment by lan786** [comment]
@bilel-bj I'm also facing rendering problem, can you help me to solve this problem?
