### ISSUE TITLE
[BUG]ImportError: ('Unable to load EGL library', 'dlopen(EGL, 10): image not found', 'EGL', None)

### ISSUE THREAD

**Issue by jiandandian2** [mkocabas/VIBE#102]
Dear doctor:
1. my operating system and the version: OSX mojave
2. python 3.7
3. no gpu

After i install packeage needed, i run the expamle code: 
python demo.py --vid_file sample_video.mp4 --output_folder output/ --display
Mistake as follow:

Traceback (most recent call last):
  File "/Users/wanghao/Desktop/VIBE-master/vibe-env/lib/python3.7/site-packages/OpenGL/platform/egl.py", line 70, in EGL
    mode=ctypes.RTLD_GLOBAL 
  File "/Users/wanghao/Desktop/VIBE-master/vibe-env/lib/python3.7/site-packages/OpenGL/platform/ctypesloader.py", line 45, in loadLibrary
    return dllType( name, mode )
  File "/usr/local/Cellar/python/3.7.5/Frameworks/Python.framework/Versions/3.7/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ('dlopen(EGL, 10): image not found', 'EGL', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 33, in <module>
    from lib.utils.renderer import Renderer
  File "/Users/wanghao/Desktop/VIBE-master/lib/utils/renderer.py", line 19, in <module>
    import pyrender
  File "/Users/wanghao/Desktop/VIBE-master/vibe-env/lib/python3.7/site-packages/pyrender/__init__.py", line 3, in <module>
    from .light import Light, PointLight, DirectionalLight, SpotLight
  File "/Users/wanghao/Desktop/VIBE-master/vibe-env/lib/python3.7/site-packages/pyrender/light.py", line 11, in <module>
    from .texture import Texture
  File "/Users/wanghao/Desktop/VIBE-master/vibe-env/lib/python3.7/site-packages/pyrender/texture.py", line 8, in <module>
    from OpenGL.GL import *
  File "/Users/wanghao/Desktop/VIBE-master/vibe-env/lib/python3.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/wanghao/Desktop/VIBE-master/vibe-env/lib/python3.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/wanghao/Desktop/VIBE-master/vibe-env/lib/python3.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/wanghao/Desktop/VIBE-master/vibe-env/lib/python3.7/site-packages/OpenGL/platform/__init__.py", line 32, in _load
    plugin.install(globals())
  File "/Users/wanghao/Desktop/VIBE-master/vibe-env/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 92, in install
    namespace[ name ] = getattr(self,name,None)
  File "/Users/wanghao/Desktop/VIBE-master/vibe-env/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "/Users/wanghao/Desktop/VIBE-master/vibe-env/lib/python3.7/site-packages/OpenGL/platform/egl.py", line 93, in GetCurrentContext
    return self.EGL.eglGetCurrentContext
  File "/Users/wanghao/Desktop/VIBE-master/vibe-env/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "/Users/wanghao/Desktop/VIBE-master/vibe-env/lib/python3.7/site-packages/OpenGL/platform/egl.py", line 73, in EGL
    raise ImportError("Unable to load EGL library", *err.args)
ImportError: ('Unable to load EGL library', 'dlopen(EGL, 10): image not found', 'EGL', None)

**Comment by NuochengTian** [comment]
俺也一样

**Comment by mkocabas** [comment]
Hi @jiandandian2,

We did not test our code on MacOS, so it is a bit difficult to figure out the problem. Windows users had a similar problem and a solution is proposed here: https://github.com/mkocabas/VIBE/issues/101#issuecomment-664180216. You may give it a try.

**Comment by lauu-nu** [comment]
Same problem
Mistake as follow:
File "src/errorchecker.pyx", line 58, in OpenGL_accelerate.errorchecker._ErrorChecker.glCheckError

**Comment by hiyyg** [comment]
@lauu-nu Did you solve it?

**Comment by yyzengca** [comment]
I have the same problem. @Mkocabas, which platform did you test your code on? Is there a virtual machine version that we can use?

**Comment by alca4** [comment]
I have the same problem with my MacOS. @mkocabas, which platform did you test your code on? Is there a virtual machine version that we can use? Thanks!
