### ISSUE TITLE
[bug] FileNotFoundError: [WinError 2] The system cannot find the file specified

### ISSUE THREAD

**Issue by AKNiloy** [mkocabas/VIBE#113]
python demo.py --vid_file sample_video.mp4 --output_folder output/ --display
Running "ffmpeg -i sample_video.mp4 -f image2 -v error /tmp\sample_video_mp4/%06d.png"
Traceback (most recent call last):
  File "demo.py", line 383, in <module>
    main(args)
  File "demo.py", line 71, in main
    image_folder, num_frames, img_shape = video_to_images(video_file, return_info=True)
  File "C:\Users\Ak Niloy\Desktop\VIBE\lib\utils\demo_utils.py", line 195, in video_to_images
    subprocess.call(command)
  File "C:\Users\Ak Niloy\.conda\envs\pyT\lib\subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\Ak Niloy\.conda\envs\pyT\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Users\Ak Niloy\.conda\envs\pyT\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified

not sure what the problem is here.
I'm using anaconda on windows 10. Installed all libraries successfully

**Comment by Suliang1027** [comment]
I met the same problem. Working on Ubuntu18.04.

(vibe-env) suliang@suliang-CNH5L:~/VIBE$ python demo.py --vid_file sample_video.mp4 --output_folder output/ --display
Running "ffmpeg -i sample_video.mp4 -f image2 -v error /tmp/sample_video_mp4/%06d.png"
Traceback (most recent call last):
  File "demo.py", line 383, in <module>
    main(args)
  File "demo.py", line 71, in main
    image_folder, num_frames, img_shape = video_to_images(video_file, return_info=True)
  File "/home/suliang/VIBE/lib/utils/demo_utils.py", line 195, in video_to_images
    subprocess.call(command)
  File "/home/suliang/anaconda3/envs/vibe-env/lib/python3.7/subprocess.py", line 339, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/home/suliang/anaconda3/envs/vibe-env/lib/python3.7/subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "/home/suliang/anaconda3/envs/vibe-env/lib/python3.7/subprocess.py", line 1551, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ffmpeg': 'ffmpeg'

**Comment by Suliang1027** [comment]
Your computer environment needs ffmpeg installed.

**Comment by minje0611** [comment]
I hope the answer is not too late.

Just modify the subprocess.py of your environment a bit.


    def __init__(self, args, bufsize=-1, executable=None,
                 stdin=None, stdout=None, stderr=None,
                 preexec_fn=None, close_fds=_PLATFORM_DEFAULT_CLOSE_FDS,
                 shell=True, cwd=None, env=None, universal_newlines=False,
                 startupinfo=None, creationflags=0,
                 restore_signals=True, start_new_session=False,
                 pass_fds=(), *, encoding=None, errors=None):

From shell=False -> True
