### ISSUE TITLE
Colab error with youtube video

### ISSUE THREAD

**Issue by nikky4D** [mkocabas/VIBE#14]
Hi, 
Using the google colab demo, I am able to install and run. However, for a youtube link, where I run this code:
`!python demo.py --vid_file https://www.youtube.com/watch?v=E7ETLLEOV4s --output_folder output/ --display`

I get the following error:

> Donwloading YouTube video "https://www.youtube.com/watch?v=E7ETLLEOV4s"
Traceback (most recent call last):
  File "demo.py", line 382, in <module>
    main(args)
  File "demo.py", line 58, in main
    video_file = download_youtube_clip(video_file, '/tmp')
  File "/content/VIBE/lib/utils/demo_utils.py", line 88, in download_youtube_clip
    return YouTube(url).streams.first().download(output_path=download_folder)
  File "/usr/local/lib/python3.6/dist-packages/pytube/__main__.py", line 88, in __init__
    self.prefetch_init()
  File "/usr/local/lib/python3.6/dist-packages/pytube/__main__.py", line 97, in prefetch_init
    self.init()
  File "/usr/local/lib/python3.6/dist-packages/pytube/__main__.py", line 143, in init
    mixins.apply_descrambler(self.player_config_args, fmt)
  File "/usr/local/lib/python3.6/dist-packages/pytube/mixins.py", line 96, in apply_descrambler
    for i in stream_data[key].split(',')
KeyError: 'url_encoded_fmt_stream_map'

**Comment by mkocabas** [comment]
Hi @nikky4D, thanks for your interest.

It is a known issue with pytube, check [here](https://github.com/nficano/pytube/issues/467). You may try other YouTube videos like this [one](https://www.youtube.com/watch?v=wPZP8Bwxplo), or download the video manually and run on local video.

**Comment by nikky4D** [comment]
Thanks. I'll check out pytube

**Comment by nikky4D** [comment]
Hi,

In case others come across this, there appears to be a fix, at least for the videos of interest to me, by installing pytube from 

> https://github.com/swiftyy-mage/pytube

and downloading the video yourself before running the code. I have not worked on integrating the new pytube with VIBE
