### ISSUE TITLE
colab Demo error

### ISSUE THREAD

**Issue by Deep-learning999** [mkocabas/VIBE#165]
when run # Run the demo
!python demo.py --vid_file sample_video.mp4 --output_folder output/ --sideview

Traceback (most recent call last):
  File "demo.py", line 403, in <module>
    main(args)
  File "demo.py", line 161, in main
    output = model(batch)[-1]
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/VIBE/lib/models/vibe.py", line 170, in forward
    smpl_output = self.regressor(feature, J_regressor=J_regressor)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/VIBE/lib/models/spin.py", line 271, in forward
    pose2rot=False
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/content/VIBE/lib/models/smpl.py", line 73, in forward
    smpl_output = super(SMPL, self).forward(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/smplx/body_models.py", line 376, in forward
    self.lbs_weights, pose2rot=pose2rot, dtype=self.dtype)
  File "/usr/local/lib/python3.6/dist-packages/smplx/lbs.py", line 205, in lbs
    J_transformed, A = batch_rigid_transform(rot_mats, J, parents, dtype=dtype)
  File "/usr/local/lib/python3.6/dist-packages/smplx/lbs.py", line 347, in batch_rigid_transform
    rel_joints.view(-1, 3, 1)).view(-1, joints.shape[1], 4, 4)

RuntimeError: view size is not compatible with input tensor's size and stride (at least one dimension spans across two contiguous subspaces). Use .reshape(...) instead.

**Comment by jiandandian2** [comment]
it works: 
rel_joints.contiguous().view(-1, 3, 1)).view(-1, joints.shape[1], 4, 4)
