### ISSUE TITLE
Error when evaluating

### ISSUE THREAD

**Issue by NoLookDefense** [mkocabas/VIBE#190]
Hello. Thanks for your excellent work.
When I am going to conduct evaluation, I saw the following error:

Traceback (most recent call last):
  File "eval.py", line 54, in <module>
    main(cfg)
  File "eval.py", line 35, in main
    test_db = ThreeDPW(set='test', seqlen=cfg.DATASET.SEQLEN, debug=cfg.DEBUG)
  File "/home/jack/Documents/VIBE/lib/dataset/threedpw.py", line 35, in __init__
    debug=debug,
  File "/home/jack/Documents/VIBE/lib/dataset/dataset_3d.py", line 41, in __init__
    self.db = self.load_db()
  File "/home/jack/Documents/VIBE/lib/dataset/dataset_3d.py", line 56, in load_db
    raise ValueError(f'{db_file} do not exists')
ValueError: data/vibe_db/3dpw_test_db.pt do not exists

I wonder are there any documents about "vibe_db/3dpw_test_db.pt"? I didn't see any references about this, like how it generates and what's its effect. 
I am looking forward to your reply

**Comment by Yamato-01** [comment]
I have the same question! I don't understand how to train with only AMASS dataset. Have you solved this issue?

**Comment by barvin04** [comment]
"_During training, VIBE takes in-the-wild images as input and predicts SMPL body model parameters using a convolutional neural network (CNN) pretrained for single-image body pose and shape estimation [37] followed by a temporal encoder and body parameter regressor used in [30]. Then, a motion discriminator takes predicted poses along with the poses sampled from the AMASS dataset and outputs a real/fake label for each sequence_" from the paper

L<sub>G</sub> = L<sub>3D</sub> + L<sub>2D</sub> + L<sub>SMPL</sub> + L<sub>adv</sub>
is the loss function

During training you'll require dataset for first, second and third term (description in paper) 
The fourth term is the adversarial penalisation which uses AMASS dataset. The idea to use AMASS is to have motion which is close to some prior motions. This has both pros and cons. 

In all, 
@NoLookDefense you'll need AMASS dataset for the adversarial section.
@Yamato-01  you will require more than just AMASS dataset which is used for adversarial loss only, after the CNN + GRU architecture.

This is what I have understood. The authors please point out if any mistakes.
