### ISSUE TITLE
RuntimeError: cannot join current thread

### ISSUE THREAD

**Issue by usernamex1x23** [mkocabas/VIBE#192]
Thanks for your interest in our research!

If you have problems running our code, please include;

1. windows 10 ,
2. Python 3.7.10,
3. 1.4.0+cu92,

4
. venv_vibe) D:\video\3\4>python demo_alter.py --vid_file sample_video.mp4 --output_folder output/ --display
Running "ffmpeg -i sample_video.mp4 -f image2 -v error /tmp\sample_video_mp4/%06d.png"
Images saved to "/tmp\sample_video_mp4"
Input video number of frames 300
Running Multi-Person-Tracker
100%|████████████████████████████████████████████████████████████████████████████████| 100/100 [01:45<00:00, 1.02s/it]
Finished. Detection + Tracking FPS 2.84
Displaying results..
WARNING: You are using a SMPL model, with only 10 shape coefficients.
Downloading: "https://download.pytorch.org/models/resnet50-19c8e357.pth" to C:\Users\Hp/.cache\torch\checkpoints\resnet50-19c8e357.pth
100%|█████████████████████████████████████████████████████████████████████████████| 97.8M/97.8M [00:42<00:00, 2.39MB/s]
WARNING: You are using a SMPL model, with only 10 shape coefficients.
=> loaded pretrained model from 'data/vibe_data\spin_model_checkpoint.pth.tar'
Performance of pretrained model on 3DPW: 56.56075477600098
Loaded pretrained weights from "data/vibe_data/vibe_model_wo_3dpw.pth.tar"
Running VIBE on each tracklet...
0%| | 0/1 [00:00<?, ?it/s]Traceback (most recent call last):
Traceback (most recent call last):
File "", line 1, in
File "demo_alter.py", line 405, in
File "D:\Newfolder\envs\venv_vibe\lib\multiprocessing\spawn.py", line 105, in spawn_main
main(args)
exitcode = _main(fd)
File "demo_alter.py", line 152, in main
File "D:\Newfolder\envs\venv_vibe\lib\multiprocessing\spawn.py", line 114, in _main
for batch in dataloader:
prepare(preparation_data)
File "D:\Newfolder\envs\venv_vibe\lib\site-packages\torch\utils\data\dataloader.py", line 279, in iter
File "D:\Newfolder\envs\venv_vibe\lib\multiprocessing\spawn.py", line 225, in prepare
_fixup_main_from_path(data['init_main_from_path'])
File "D:\Newfolder\envs\venv_vibe\lib\multiprocessing\spawn.py", line 277, in _fixup_main_from_path
run_name="mp_main")
File "D:\Newfolder\envs\venv_vibe\lib\runpy.py", line 263, in run_path
pkg_name=pkg_name, script_name=fname)
File "D:\Newfolder\envs\venv_vibe\lib\runpy.py", line 96, in _run_module_code
mod_name, mod_spec, pkg_name, script_name)
File "D:\Newfolder\envs\venv_vibe\lib\runpy.py", line 85, in run_code
exec(code, run_globals)
File "D:\video\3\4\demo_alter.py", line 22, in
import torch
File "D:\Newfolder\envs\venv_vibe\lib\site-packages\torch_init.py", line 81, in
from torch._C import *
ImportError: DLL load failed: The paging file is too small for this operation to complete.
return _MultiProcessingDataLoaderIter(self)
File "D:\Newfolder\envs\venv_vibe\lib\site-packages\torch\utils\data\dataloader.py", line 719, in init
w.start()
File "D:\Newfolder\envs\venv_vibe\lib\multiprocessing\process.py", line 112, in start
self._popen = self._Popen(self)
File "D:\Newfolder\envs\venv_vibe\lib\multiprocessing\context.py", line 223, in _Popen
return _default_context.get_context().Process._Popen(process_obj)
File "D:\Newfolder\envs\venv_vibe\lib\multiprocessing\context.py", line 322, in _Popen
return Popen(process_obj)
File "D:\Newfolder\envs\venv_vibe\lib\multiprocessing\popen_spawn_win32.py", line 89, in init
reduction.dump(process_obj, to_child)
File "D:\Newfolder\envs\venv_vibe\lib\multiprocessing\reduction.py", line 60, in dump
ForkingPickler(file, protocol).dump(obj)
BrokenPipeError: [Errno 32] Broken pipe
Exception ignored in: <function tqdm.del at 0x000001C902E0D558>
Traceback (most recent call last):
File "D:\Newfolder\envs\venv_vibe\lib\site-packages\tqdm_tqdm.py", line 931, in del
self.close()
File "D:\Newfolder\envs\venv_vibe\lib\site-packages\tqdm_tqdm.py", line 1133, in close
self._decr_instances(self)
File "D:\Newfolder\envs\venv_vibe\lib\site-packages\tqdm_tqdm.py", line 496, in _decr_instances
cls.monitor.exit()
File "D:\Newfolder\envs\venv_vibe\lib\site-packages\tqdm_monitor.py", line 52, in exit
self.join()
File "D:\Newfolder\envs\venv_vibe\lib\threading.py", line 1041, in join
raise RuntimeError("cannot join current thread")
RuntimeError: cannot join current thread,

Specifically, if you have an issue with pyrender or OpenGL setup & installation, please refer to pyrender [docs](https://pyrender.readthedocs.io/en/latest/) or [github issues](https://github.com/mmatl/pyrender/issues).

**Comment by joaodafonseca** [comment]
having the same issue. Any developments on this? appreciated

**Comment by Mario-LuX** [comment]
I solve this when running demo with my Windows 10 PC
The problem is the line 146 of demo_altar.py
dataloader = DataLoader(dataset, batch_size=args.vibe_batch_size, num_workers=16)
just delete num_workers=16 or set it to 0. I did this and it works.
Actually I met with multiple problems with num_workers in newly released Pytorch. When using a PC with only single GPU, it will easily cause CUDA out of memory in the middle of running a script if you set this num_workers to something other than 0.
