### ISSUE TITLE
[BUG] Run demo with trained model

### ISSUE THREAD

**Issue by GuyTevet** [mkocabas/VIBE#193]
Thanks for your great work!
Can I run the demo with my own trained model (trained with train.py)?
Naively trying to pass the resulted `model_best.pth.tar` to `VIBE_Demo(pretrained=...)` runs into the following error:

```
Traceback (most recent call last):
  File "demo.py", line 431, in <module>
    main(args)
  File "demo.py", line 122, in main
    pretrained=args.model_tar_path,
  File "/disk2/guytevet/VIBE/lib/models/vibe.py", line 148, in __init__
    self.hmr.load_state_dict(checkpoint['model'], strict=False)
KeyError: 'model'
```

OS - Ubuntu 18.04.5 LTS
Python venv as you specified.

Thanks,

**Comment by GuyTevet** [comment]
Pointing on the provided `data/vibe_data/vibe_model_w_3dpw.pth.tar` causes the same error.

**Comment by victory-12374** [comment]
Why not try to run the demo.py in the "https://colab.research.google.com/drive/1dFfwxZ52MN86FA6uFNypMEdFShd2euQA#scrollTo=m_6yTVe9DMsV" which is provided by the author?

**Comment by GuyTevet** [comment]
Thanks @victory-12374! 

I'll clear myself - I have no problem running the demo as specified by the authors (`python demo.py --vid_file sample_video.mp4 --output_folder output/ --display
`). 

I'm now trying to run it with a different model than the default one. Specifically, a model I trained myself using `train.py`. This involves a minor code change as described in my first message.

**Comment by Ironbrotherstyle** [comment]
> Thanks @victory-12374!
> 
> I'll clear myself - I have no problem running the demo as specified by the authors (`python demo.py --vid_file sample_video.mp4 --output_folder output/ --display `).
> 
> I'm now trying to run it with a different model than the default one. Specifically, a model I trained myself using `train.py`. This involves a minor code change as described in my first message.

you need specify the model path in config.yaml, after TRAIN: PRETRAINED:

**Comment by ZxyLinkstart** [comment]
> Thanks for your great work!
> Can I run the demo with my own trained model (trained with train.py)?
> Naively trying to pass the resulted `model_best.pth.tar` to `VIBE_Demo(pretrained=...)` runs into the following error:
> 
> ```
> Traceback (most recent call last):
>   File "demo.py", line 431, in <module>
>     main(args)
>   File "demo.py", line 122, in main
>     pretrained=args.model_tar_path,
>   File "/disk2/guytevet/VIBE/lib/models/vibe.py", line 148, in __init__
>     self.hmr.load_state_dict(checkpoint['model'], strict=False)
> KeyError: 'model'
> ```
> 
> OS - Ubuntu 18.04.5 LTS
> Python venv as you specified.
> 
> Thanks,

Hello, has this problem been solved now? I also encountered the same problem.😂

**Comment by mlkorra** [comment]
> I'll clear myself - I have no problem running the demo as specified by the authors (`python demo.py --vid_file sample_video.mp4 --output_folder output/ --display `).

Hi @GuyTevet , have you encountered any similar error whie running demo.py with the given model on a new video file w.r.t the yolov3 weights?

> Traceback (most recent call last):
>   File "demo.py", line 415, in <module>
>     main(args)
>   File "demo.py", line 95, in main
>     yolo_img_size=args.yolo_img_size,
>   File "/home/krd/3DMeshfromVideos/VIBE/VIBE/vibe-env/lib/python3.7/site-packages/multi_person_tracker/mpt.py", line 53, in __init__
>     device=self.device, img_size=yolo_img_size, person_detector=True, video=True, return_dict=True
>   File "/home/krd/3DMeshfromVideos/VIBE/VIBE/vibe-env/lib/python3.7/site-packages/yolov3/yolo.py", line 51, in __init__
>     self.model.load_darknet_weights(weights_path)
>   File "/home/krd/3DMeshfromVideos/VIBE/VIBE/vibe-env/lib/python3.7/site-packages/yolov3/models.py", line 315, in load_darknet_weights
>     conv_w = torch.from_numpy(weights[ptr : ptr + num_w]).view_as(conv_layer.weight)
> RuntimeError: shape '[512, 256, 3, 3]' is invalid for input of size 285006
>
