### ISSUE TITLE
[BUG] Colab failed to access data

### ISSUE THREAD

**Issue by snitchjinx** [mkocabas/VIBE#239]
Hello! I'm executing the project in Google Colab. However, the data failed to download at:
`!source scripts/prepare_data.sh`

Below is the error message:
```
# Download pretrained weights and SMPL data
!source scripts/prepare_data.sh
Traceback (most recent call last):
  File "/usr/local/bin/gdown", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/gdown/cli.py", line 61, in main
    quiet=args.quiet,
  File "/usr/local/lib/python3.7/dist-packages/gdown/download.py", line 52, in download
    res = sess.get(url, stream=True)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 543, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 516, in request
    prep = self.prepare_request(req)
  File "/usr/local/lib/python3.7/dist-packages/requests/sessions.py", line 459, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 314, in prepare
    self.prepare_url(url, params)
  File "/usr/local/lib/python3.7/dist-packages/requests/models.py", line 388, in prepare_url
    raise MissingSchema(error)
requests.exceptions.MissingSchema: Invalid URL '': No schema supplied. Perhaps you meant [http://](http:)?
unzip:  cannot find or open vibe_data.zip, vibe_data.zip.zip or vibe_data.zip.ZIP.
rm: cannot remove 'vibe_data.zip': No such file or directory
mv: cannot stat 'data/vibe_data/sample_video.mp4': No such file or directory
mv: cannot stat 'data/vibe_data/yolov3.weights': No such file or directory```

**Comment by ksh7621** [comment]
same error

**Comment by aarunjith** [comment]
this seems to be a gdown issue
i had to manually download the zip and then remove the gdown link from prepare_data.sh

**Comment by snitchjinx** [comment]
> 

That's a good solution, but for Colab uploading zip is too consuming.

**Comment by jkcg-learning** [comment]
you may please upgrade the gdown version to 4.4.0 in the requirements.txt file.

**Comment by eliohead** [comment]
You can alternatively use Pydrive to download the file manually

**Comment by EmileDqy** [comment]
Hi, I've come across the exact same issue and I have found the solution.

Replace the gdown command in scripts/prepare_data.sh with this:

`gdown "https://drive.google.com/uc?id=1untXhYOLQtpNEy4GTY_0fL_H-k6cTf_r&export=download&confirm=t"`

The `&export=download&confirm=t` part is used to accept the download of the large file.

Have a nice day :)

**Comment by yinkangning0124** [comment]
> Hi, I've come across the exact same issue and I have found the solution.
> 
> Replace the gdown command in scripts/prepare_data.sh with this:
> 
> `gdown "https://drive.google.com/uc?id=1untXhYOLQtpNEy4GTY_0fL_H-k6cTf_r&export=download&confirm=t"`
> 
> The `&export=download&confirm=t` part is used to accept the download of the large file.
> 
> Have a nice day :)

Perfectly solve this problem. Thankxxx
