### ISSUE TITLE
[BUG]About AMASS Datasets‘s 'mocap_framerate is not a file in the archive' problem

### ISSUE THREAD

**Issue by syan2018** [mkocabas/VIBE#243]
It needs fixup all the `data['mocap_framerate']` in lib/data_utils/amass_utils.py to `data['mocap_frame_rate']`

In the newest AMASS，the key word 'mocap_framerate' has been changed

Hope you guys never get puzzled as I am lol

**Comment by Songinpyo** [comment]
I have a question

I fixed up all data['mocap_framerate'] in lib/data_utils/amass_utils.py to data['mocap_frame_rate']
but, still got errors

```
Traceback (most recent call last):
  File "lib/data_utils/amass_utils.py", line 147, in <module>
    db = read_data(args.dir, sequences=all_sequences)
  File "lib/data_utils/amass_utils.py", line 69, in read_data
    thetas, vid_names = read_single_sequence(seq_folder, seq_name)
  File "lib/data_utils/amass_utils.py", line 99, in read_single_sequence
    mocap_framerate = int(data['mocap_frame_rate'])
  File "/home/inpyosong/anaconda3/envs/vibe-env/lib/python3.7/site-packages/numpy/lib/npyio.py", line 260, in __getitem__
    raise KeyError("%s is not a file in the archive" % key)
KeyError: 'mocap_frame_rate is not a file in the archive'
```

I downloaded SMPL-X N amass.
Is it right to do it on SMPL-X N or SMPL-H

**Comment by 1324833746** [comment]
> 

Hello, may I ask if you know which format of dataset to use?

**Comment by 1324833746** [comment]
> I have a question
> 
> I fixed up all data['mocap_framerate'] in lib/data_utils/amass_utils.py to data['mocap_frame_rate'] but, still got errors
> 
> ```
> Traceback (most recent call last):
>   File "lib/data_utils/amass_utils.py", line 147, in <module>
>     db = read_data(args.dir, sequences=all_sequences)
>   File "lib/data_utils/amass_utils.py", line 69, in read_data
>     thetas, vid_names = read_single_sequence(seq_folder, seq_name)
>   File "lib/data_utils/amass_utils.py", line 99, in read_single_sequence
>     mocap_framerate = int(data['mocap_frame_rate'])
>   File "/home/inpyosong/anaconda3/envs/vibe-env/lib/python3.7/site-packages/numpy/lib/npyio.py", line 260, in __getitem__
>     raise KeyError("%s is not a file in the archive" % key)
> KeyError: 'mocap_frame_rate is not a file in the archive'
> ```
> 
> I downloaded SMPL-X N amass. Is it right to do it on SMPL-X N or SMPL-H

Hello, may I ask if you know which format of dataset to use?

**Comment by neverstoplearn** [comment]
> I

have you fix it? I meet the same error.

**Comment by neverstoplearn** [comment]
> > I have a question
> > I fixed up all data['mocap_framerate'] in lib/data_utils/amass_utils.py to data['mocap_frame_rate'] but, still got errors
> > ```
> > Traceback (most recent call last):
> >   File "lib/data_utils/amass_utils.py", line 147, in <module>
> >     db = read_data(args.dir, sequences=all_sequences)
> >   File "lib/data_utils/amass_utils.py", line 69, in read_data
> >     thetas, vid_names = read_single_sequence(seq_folder, seq_name)
> >   File "lib/data_utils/amass_utils.py", line 99, in read_single_sequence
> >     mocap_framerate = int(data['mocap_frame_rate'])
> >   File "/home/inpyosong/anaconda3/envs/vibe-env/lib/python3.7/site-packages/numpy/lib/npyio.py", line 260, in __getitem__
> >     raise KeyError("%s is not a file in the archive" % key)
> > KeyError: 'mocap_frame_rate is not a file in the archive'
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I downloaded SMPL-X N amass. Is it right to do it on SMPL-X N or SMPL-H
> 
> Hello, may I ask if you know which format of dataset to use?

have you fix the error?thanks.

**Comment by sshable** [comment]
Any fix to this issue, I am also getting the same error?
Thanks

**Comment by sshable** [comment]
Got a fix!

In ACCAD folder for every subject there is a 'neutral_stagei.npz' file. This file doesn't have a motion_frame_rate.npy file.
That's why the error. Delete this file from each folder and the script will run successfully. 

Let me know if it helps!
