### ISSUE TITLE
[BUG] 'EGL: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by zhiboniu** [mkocabas/VIBE#245]
Thanks for your interest in our research!

If you have problems running our code, please include;

1. your operating system and the version,
2. your python version,
3. your pytorch version,
4. the stack trace of the error that you see,

Specifically, if you have an issue with pyrender or OpenGL setup & installation, please refer to pyrender [docs](https://pyrender.readthedocs.io/en/latest/) or [github issues](https://github.com/mmatl/pyrender/issues).

I got this error while run the demo.py, anyone know how to fix this problem?

Traceback (most recent call last):
  File "/xxx/VIBE/vibe-env/lib/python3.7/site-packages/OpenGL/platform/egl.py", line 70, in EGL
    mode=ctypes.RTLD_GLOBAL
  File "/xxx/VIBE/vibe-env/lib/python3.7/site-packages/OpenGL/platform/ctypesloader.py", line 45, in loadLibrary
    return dllType( name, mode )
  File "/usr/local/lib/python3.7/ctypes/__init__.py", line 356, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ('EGL: cannot open shared object file: No such file or directory', 'EGL', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 35, in <module>
    from lib.utils.renderer import Renderer

...

    raise ImportError("Unable to load EGL library", *err.args)
ImportError: ('Unable to load EGL library', 'EGL: cannot open shared object file: No such file or directory', 'EGL', None)

**Comment by Kirehuang** [comment]
hi! i had solved this problems on ubuntu18.4  by the following command:
`apt-get install libglfw3-dev libgles2-mesa-dev`
`sudo apt install freeglut3-dev`
