### ISSUE TITLE
pyrenderer Error！

### ISSUE THREAD

**Issue by Llhai** [mkocabas/VIBE#32]
**Hi！this is my problem，when i ran “python demo.py --vid_file sample_video.mp4 --output_folder output/ --display ”， I get the following error：**
--------------------------
```
Traceback (most recent call last):
  File "C:\Users\41656\Anaconda3\envs\pyVIBE\lib\site-packages\OpenGL\platform\egl.py", line 71, in EGL
    mode=ctypes.RTLD_GLOBAL
  File "C:\Users\41656\Anaconda3\envs\pyVIBE\lib\site-packages\OpenGL\platform\ctypesloader.py", line 45, in loadLibrary
    return dllType( name, mode )
  File "C:\Users\41656\Anaconda3\envs\pyVIBE\lib\ctypes\__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: [WinError 126] 找不到指定的模块。
```
```
Traceback (most recent call last):
  File "demo.py", line 33, in <module>
    from lib.utils.renderer import Renderer
  File "D:\Project\Python\VIBE-master\lib\utils\renderer.py", line 19, in <module>
    import pyrender
  File "C:\Users\41656\Anaconda3\envs\pyVIBE\lib\site-packages\pyrender\__init__.py", line 3, in <module>
    from .light import Light, PointLight, DirectionalLight, SpotLight
  File "C:\Users\41656\Anaconda3\envs\pyVIBE\lib\site-packages\pyrender\light.py", line 11, in <module>
    from .texture import Texture
  File "C:\Users\41656\Anaconda3\envs\pyVIBE\lib\site-packages\pyrender\texture.py", line 8, in <module>
    from OpenGL.GL import *
  File "C:\Users\41656\Anaconda3\envs\pyVIBE\lib\site-packages\OpenGL\GL\__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "C:\Users\41656\Anaconda3\envs\pyVIBE\lib\site-packages\OpenGL\error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "C:\Users\41656\Anaconda3\envs\pyVIBE\lib\site-packages\OpenGL\platform\__init__.py", line 35, in <module>
    _load()
  File "C:\Users\41656\Anaconda3\envs\pyVIBE\lib\site-packages\OpenGL\platform\__init__.py", line 32, in _load
    plugin.install(globals())
  File "C:\Users\41656\Anaconda3\envs\pyVIBE\lib\site-packages\OpenGL\platform\baseplatform.py", line 92, in install
    namespace[ name ] = getattr(self,name,None)
  File "C:\Users\41656\Anaconda3\envs\pyVIBE\lib\site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "C:\Users\41656\Anaconda3\envs\pyVIBE\lib\site-packages\OpenGL\platform\egl.py", line 94, in GetCurrentContext
    return self.EGL.eglGetCurrentContext
  File "C:\Users\41656\Anaconda3\envs\pyVIBE\lib\site-packages\OpenGL\platform\baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "C:\Users\41656\Anaconda3\envs\pyVIBE\lib\site-packages\OpenGL\platform\egl.py", line 74, in EGL
    raise ImportError("Unable to load EGL library", *err.args)
ImportError: ('Unable to load EGL library', 22, '找不到指定的模块。', None, 126, None, 'GL', None)
```
------------------------------------------------------------------------------------------------------
**I run this command on win10 Thanks for your support！！**

**Comment by mkocabas** [comment]
Hi @Llhai,

This issue is related to pyrender installation, please refer to pyrender readme and github issues. Besides, VIBE isn't tested on windows and I would be happy if you let us know what is needed to run it on windows.
