### ISSUE TITLE
Error when using --tracking_method pose

### ISSUE THREAD

**Issue by GCCFeli** [mkocabas/VIBE#33]
It looks the code use absolute path when looking for openposetrack

Here is the traceback:

```
Traceback (most recent call last):
  File "demo.py", line 383, in <module>
    main(args)
  File "demo.py", line 83, in main
    tracking_results = run_posetracker(video_file, staf_folder=args.staf_dir, display=args.display)
  File "/home/feli/git/VIBE/lib/utils/pose_tracker.py", line 91, in run_posetracker
    staf_folder=staf_folder
  File "/home/feli/git/VIBE/lib/utils/pose_tracker.py", line 32, in run_openpose
    os.chdir(staf_folder)
FileNotFoundError: [Errno 2] No such file or directory: '/home/mkocabas/developments/openposetrack'
```

**Comment by mkocabas** [comment]
You should pass `--staf_dir YOUR_STAF_FOLDER` argument to `demo.py`. Default `staf_dir` parameter points to my local STAF clone, this is why you got this error.

**Comment by jabberrock** [comment]
It looks like STAF no longer builds. `sh getModels.sh` can no longer resolve posefs1.perception.cs.cmu.edu. Where can we get STAF from?
