### ISSUE TITLE
How can I get an .obj file directly from a single rgb image? Any available demo codes for that?

### ISSUE THREAD

**Issue by guodewen** [mkocabas/VIBE#41]

**Comment by guodewen** [comment]
I tried to run the demo codes on my macOS. However, egl error just occurs.

Traceback (most recent call last):
  File "/Users/guodewen/anaconda3/envs/vibe-env/lib/python3.7/site-packages/OpenGL/platform/egl.py", line 70, in EGL
    mode=ctypes.RTLD_GLOBAL 
  File "/Users/guodewen/anaconda3/envs/vibe-env/lib/python3.7/site-packages/OpenGL/platform/ctypesloader.py", line 45, in loadLibrary
    return dllType( name, mode )
  File "/Users/guodewen/anaconda3/envs/vibe-env/lib/python3.7/ctypes/__init__.py", line 364, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: ('dlopen(EGL, 10): image not found', 'EGL', None)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 33, in <module>
    from lib.utils.renderer import Renderer
  File "/Users/guodewen/Desktop/VIBE/lib/utils/renderer.py", line 19, in <module>
    import pyrender
  File "/Users/guodewen/anaconda3/envs/vibe-env/lib/python3.7/site-packages/pyrender/__init__.py", line 3, in <module>
    from .light import Light, PointLight, DirectionalLight, SpotLight
  File "/Users/guodewen/anaconda3/envs/vibe-env/lib/python3.7/site-packages/pyrender/light.py", line 11, in <module>
    from .texture import Texture
  File "/Users/guodewen/anaconda3/envs/vibe-env/lib/python3.7/site-packages/pyrender/texture.py", line 8, in <module>
    from OpenGL.GL import *
  File "/Users/guodewen/anaconda3/envs/vibe-env/lib/python3.7/site-packages/OpenGL/GL/__init__.py", line 3, in <module>
    from OpenGL import error as _error
  File "/Users/guodewen/anaconda3/envs/vibe-env/lib/python3.7/site-packages/OpenGL/error.py", line 12, in <module>
    from OpenGL import platform, _configflags
  File "/Users/guodewen/anaconda3/envs/vibe-env/lib/python3.7/site-packages/OpenGL/platform/__init__.py", line 35, in <module>
    _load()
  File "/Users/guodewen/anaconda3/envs/vibe-env/lib/python3.7/site-packages/OpenGL/platform/__init__.py", line 32, in _load
    plugin.install(globals())
  File "/Users/guodewen/anaconda3/envs/vibe-env/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 92, in install
    namespace[ name ] = getattr(self,name,None)
  File "/Users/guodewen/anaconda3/envs/vibe-env/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "/Users/guodewen/anaconda3/envs/vibe-env/lib/python3.7/site-packages/OpenGL/platform/egl.py", line 93, in GetCurrentContext
    return self.EGL.eglGetCurrentContext
  File "/Users/guodewen/anaconda3/envs/vibe-env/lib/python3.7/site-packages/OpenGL/platform/baseplatform.py", line 14, in __get__
    value = self.fget( obj )
  File "/Users/guodewen/anaconda3/envs/vibe-env/lib/python3.7/site-packages/OpenGL/platform/egl.py", line 73, in EGL
    raise ImportError("Unable to load EGL library", *err.args)
ImportError: ('Unable to load EGL library', 'dlopen(EGL, 10): image not found', 'EGL', None)

**Comment by mkocabas** [comment]
VIBE works for videos only, please see [SPIN](https://github.com/nkolot/SPIN) to work with single images.

**Comment by Primate92587** [comment]
this is actually an import error and comes from this line :  os.environ['PYOPENGL_PLATFORM'] = 'egl'. I'm getting the same error and don't know how to fix this.

**Comment by ruleGreen** [comment]
is this fixed? I encountered this problem too.
