### ISSUE TITLE
[BUG] Demo code crashing with temporal tracking

### ISSUE THREAD

**Issue by Tetsujinfr** [mkocabas/VIBE#48]
1. OS: running the demo notebook on google Colab
2. your python version: 3.6.9
3. your pytorch version: 1.4.0

When running the demo instruction below, I have an error. It occurs when I try to run with the temporal SMPLify algo as per the demo document:

`!python demo.py --vid_file sample_video.mp4 --output_folder output/ --tracking_method pose --display --run_smplify`

then I get the following error (it seems some files are missing in the repository):
`Running "ffmpeg -i sample_video.mp4 -f image2 -v error /tmp/sample_video_mp4/%06d.png"
Images saved to "/tmp/sample_video_mp4"
Input video number of frames 300
Traceback (most recent call last):
  File "demo.py", line 383, in <module>
    main(args)
  File "demo.py", line 83, in main
    tracking_results = run_posetracker(video_file, staf_folder=args.staf_dir, display=args.display)
  File "/content/VIBE/VIBE/lib/utils/pose_tracker.py", line 91, in run_posetracker
    staf_folder=staf_folder
  File "/content/VIBE/VIBE/lib/utils/pose_tracker.py", line 32, in run_openpose
    os.chdir(staf_folder)
FileNotFoundError: [Errno 2] No such file or directory: '/home/mkocabas/developments/openposetrack'`

Please can you help? thanks a lot

**Comment by Tetsujinfr** [comment]
ok sorry, did not see this issue has been already raised and closed. closing this consequently.
Great research work btw!

**Comment by Tetsujinfr** [comment]
Pretty cool model, works reasonably well. I have run a couple of inferences on this video:
https://youtu.be/1xl5YXRiOuc
Some artifacts but overall the quality is good I think.
