### ISSUE TITLE
Can the code be run on CPU?

### ISSUE THREAD

**Issue by uday701** [mkocabas/VIBE#73]
Can you please let me know whether I can run code on CPU?

**Comment by mkocabas** [comment]
Yes, it can. You may give it a try.

**Comment by uday701** [comment]
Actually code is not able to run on CPU.When I tried to run on CPU it is showing error like


Running Multi-Person-Tracker
  0%|                                                                                                                | 0/26 [00:00<?, ?it/s]Traceback (most recent call last):
  File "/home/uday/vibe/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 761, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/lib/python3.7/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 920, in wait
    ready = selector.select(timeout)
  File "/usr/lib/python3.7/selectors.py", line 415, in select
    fd_event_list = self._selector.poll(timeout)
  File "/home/uday/vibe/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 4213) is killed by signal: Killed. 

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 383, in <module>
    main(args)
  File "demo.py", line 94, in main
    tracking_results = mot(image_folder)
  File "/home/uday/vibe/lib/python3.7/site-packages/multi_person_tracker/mpt.py", line 194, in __call__
    trackers = self.run_tracker(dataloader)
  File "/home/uday/vibe/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 15, in decorate_context
    return func(*args, **kwargs)
  File "/home/uday/vibe/lib/python3.7/site-packages/multi_person_tracker/mpt.py", line 75, in run_tracker
    for batch in tqdm(dataloader):
  File "/home/uday/vibe/lib/python3.7/site-packages/tqdm/_tqdm.py", line 979, in __iter__
    for obj in iterable:
  File "/home/uday/vibe/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/home/uday/vibe/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 841, in _next_data
    idx, data = self._get_data()
  File "/home/uday/vibe/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 808, in _get_data
    success, data = self._try_get_data()
  File "/home/uday/vibe/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 774, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 4213) exited unexpectedly

I tried a lot to overcome this error but without success.Please let me know if I have to modify anything for running the code.
