### ISSUE TITLE
Running Multi-Person-Tracker

### ISSUE THREAD

**Issue by NilanjPatel** [mkocabas/VIBE#87]
1. your operating system and the version = raspberrian os 
2. your python version = 3.7
3. your pytorch version= 1.3.0a0 
4. the stack trace of the error that I show is as bellow

`Running "ffmpeg -i sample_video.mp4 -f image2 -v error /tmp/sample_video_mp4/%06d.png"
Images saved to "/tmp/sample_video_mp4"
Input video number of frames {num_frames}
Downloading files from https://raw.githubusercontent.com/mkocabas/yolov3-pytorch/master/yolov3/config/yolov3.cfg
--2020-06-07 14:06:14--  https://raw.githubusercontent.com/mkocabas/yolov3-pytorch/master/yolov3/config/yolov3.cfg
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 199.232.20.133
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|199.232.20.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 8338 (8.1K) [text/plain]
Saving to: ‘/home/pi/.torch/config/yolov3.cfg’

yolov3.cfg                        100%[==========================================================>]   8.14K  --.-KB/s    in 0.006s  

2020-06-07 14:06:15 (1.23 MB/s) - ‘/home/pi/.torch/config/yolov3.cfg’ saved [8338/8338]

Running Multi-Person-Tracker
  0%|                                                                                                         | 0/25 [00:00<?, ?it/s]ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
ERROR: Unexpected bus error encountered in worker. This might be caused by insufficient shared memory (shm).
Traceback (most recent call last):
  File "/home/pi/Desktop/VIBE/vibe-env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 724, in _try_get_data
    data = self._data_queue.get(timeout=timeout)
  File "/usr/lib/python3.7/multiprocessing/queues.py", line 104, in get
    if not self._poll(timeout):
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 257, in poll
    return self._poll(timeout)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 414, in _poll
    r = wait([self], timeout)
  File "/usr/lib/python3.7/multiprocessing/connection.py", line 925, in wait
    timeout = deadline - time.monotonic()
  File "/home/pi/Desktop/VIBE/vibe-env/lib/python3.7/site-packages/torch/utils/data/_utils/signal_handling.py", line 66, in handler
    _error_if_any_worker_fails()
RuntimeError: DataLoader worker (pid 1459) is killed by signal: Bus error. It is possible that dataloader's workers are out of shared memory. Please try to raise your shared memory limit.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 383, in <module>
    main(args)
  File "demo.py", line 94, in main
    tracking_results = mot(image_folder)
  File "/home/pi/Desktop/VIBE/vibe-env/lib/python3.7/site-packages/multi_person_tracker/mpt.py", line 194, in __call__
    trackers = self.run_tracker(dataloader)
  File "/home/pi/Desktop/VIBE/vibe-env/lib/python3.7/site-packages/torch/autograd/grad_mode.py", line 49, in decorate_no_grad
    return func(*args, **kwargs)
  File "/home/pi/Desktop/VIBE/vibe-env/lib/python3.7/site-packages/multi_person_tracker/mpt.py", line 75, in run_tracker
    for batch in tqdm(dataloader):
  File "/home/pi/Desktop/VIBE/vibe-env/lib/python3.7/site-packages/tqdm/_tqdm.py", line 897, in __iter__
    for obj in iterable:
  File "/home/pi/Desktop/VIBE/vibe-env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 804, in __next__
    idx, data = self._get_data()
  File "/home/pi/Desktop/VIBE/vibe-env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 771, in _get_data
    success, data = self._try_get_data()
  File "/home/pi/Desktop/VIBE/vibe-env/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 737, in _try_get_data
    raise RuntimeError('DataLoader worker (pid(s) {}) exited unexpectedly'.format(pids_str))
RuntimeError: DataLoader worker (pid(s) 1459, 1460, 1461, 1462, 1463, 1464, 1465, 1466) exited unexpectedly`

**Comment by mkocabas** [comment]
Hi @NilanjPatel,

Looks like the memory of your device is insufficient to run the tracker. You can try to reduce the num_workers, batch_size parameters to see whether it fits into the memory.
