### ISSUE TITLE
about running the demo

### ISSUE THREAD

**Issue by FrankMelon1** [mkocabas/VIBE#88]
I would like to thank you first for the great scientific contribution made in the paper.
I got an error when trying to run the demo, This is the error message got:
 python demo.py --vid_file https://www.youtube.com/watch?v=wPZP8Bwxplo --output_folder output/ --display
Traceback (most recent call last):
  File "demo.py", line 29, in <module>
    from multi_person_tracker import MPT
  File "/home/wutao/anaconda3/envs/vibe-env/lib/python3.7/site-packages/multi_person_tracker/__init__.py", line 1, in <module>
    from .sort import Sort
  File "/home/wutao/anaconda3/envs/vibe-env/lib/python3.7/site-packages/multi_person_tracker/sort.py", line 21, in <module>
    from numba import jit
  File "/home/wutao/anaconda3/envs/vibe-env/lib/python3.7/site-packages/numba/__init__.py", line 196, in <module>
    import numba.typed
  File "/home/wutao/anaconda3/envs/vibe-env/lib/python3.7/site-packages/numba/typed/__init__.py", line 3, in <module>
    from .typeddict import Dict
  File "/home/wutao/anaconda3/envs/vibe-env/lib/python3.7/site-packages/numba/typed/typeddict.py", line 19, in <module>
    @njit
  File "/home/wutao/anaconda3/envs/vibe-env/lib/python3.7/site-packages/numba/decorators.py", line 238, in njit
    return jit(*args, **kws)
  File "/home/wutao/anaconda3/envs/vibe-env/lib/python3.7/site-packages/numba/decorators.py", line 175, in jit
    return wrapper(pyfunc)
  File "/home/wutao/anaconda3/envs/vibe-env/lib/python3.7/site-packages/numba/decorators.py", line 191, in wrapper
    **dispatcher_args)
  File "/home/wutao/anaconda3/envs/vibe-env/lib/python3.7/site-packages/numba/dispatcher.py", line 650, in __init__
    self.targetctx = self.targetdescr.target_context
  File "/home/wutao/anaconda3/envs/vibe-env/lib/python3.7/site-packages/numba/targets/registry.py", line 50, in target_context
    return self._toplevel_target_context
  File "/home/wutao/anaconda3/envs/vibe-env/lib/python3.7/site-packages/numba/utils.py", line 390, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "/home/wutao/anaconda3/envs/vibe-env/lib/python3.7/site-packages/numba/targets/registry.py", line 34, in _toplevel_target_context
    return cpu.CPUContext(self.typing_context)
  File "/home/wutao/anaconda3/envs/vibe-env/lib/python3.7/site-packages/numba/targets/base.py", line 260, in __init__
    self.init()
  File "/home/wutao/anaconda3/envs/vibe-env/lib/python3.7/site-packages/numba/compiler_lock.py", line 32, in _acquire_compile_lock
    return func(*args, **kwargs)
  File "/home/wutao/anaconda3/envs/vibe-env/lib/python3.7/site-packages/numba/targets/cpu.py", line 51, in init
    self._internal_codegen = codegen.JITCPUCodegen("numba.exec")
  File "/home/wutao/anaconda3/envs/vibe-env/lib/python3.7/site-packages/numba/targets/codegen.py", line 628, in __init__
    self._init(self._llvm_module)
  File "/home/wutao/anaconda3/envs/vibe-env/lib/python3.7/site-packages/numba/targets/codegen.py", line 637, in _init
    tm = target.create_target_machine(**tm_options)
TypeError: create_target_machine() got an unexpected keyword argument 'jitdebug'

Do you know how to solve this issue?
Thanks a lot for your support.

**Comment by longbowzhang** [comment]
Exactly the same error for me.
Python = 3.7.7 torch=1.4.0
OS="Ubuntu" with VERSION="16.04.6 LTS (Xenial Xerus)"

**Comment by fyllong** [comment]
I have updated numba from 0.45.1 to 0.49.1 and this error is solved.

**Comment by athn-nik** [comment]
Thanks @fyllong. I am closing this.

**Comment by hcp6897** [comment]
I have solved same problem by down llvmlite
**pip install -U llvmlite==0.32.1**
hope it can helps anybody!
